"""added approve datetime field

Revision ID: 37afb305a208
Revises: e808b8e45923
Create Date: 2025-01-07 18:11:02.733585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37afb305a208'
down_revision = 'e808b8e45923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_ticket_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve_datetime', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_ticket_payments', schema=None) as batch_op:
        batch_op.drop_column('approve_datetime')

    # ### end Alembic commands ###
