"""added more fields to event ticket

Revision ID: 5845204c4a96
Revises: d8dd1cd5ac63
Create Date: 2024-12-15 16:26:01.038140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5845204c4a96'
down_revision = 'd8dd1cd5ac63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_datetime', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('payment_datetime', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('cancel_datetime', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.drop_column('cancel_datetime')
        batch_op.drop_column('payment_datetime')
        batch_op.drop_column('create_datetime')

    # ### end Alembic commands ###
