"""added note field

Revision ID: 65a54f253b47
Revises: 3ec49bd16ec1
Create Date: 2025-01-16 14:33:14.299010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a54f253b47'
down_revision = '3ec49bd16ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_ticket_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_ticket_payments', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
