"""added student class and note fields to the member model

Revision ID: 6fdbd7c7cded
Revises: b5e20d54f826
Create Date: 2025-02-15 10:54:46.950995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdbd7c7cded'
down_revision = 'b5e20d54f826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_info', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('student_class')

    # ### end Alembic commands ###
