"""added checkin datetime field

Revision ID: 75cebbdf14f3
Revises: b9a443fae231
Create Date: 2025-01-07 16:46:52.749149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cebbdf14f3'
down_revision = 'b9a443fae231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_datetime', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.drop_column('checkin_datetime')

    # ### end Alembic commands ###
