"""added holder id field to the ticket model

Revision ID: a5f510da307e
Revises: af38be27fc2c
Create Date: 2024-12-28 10:28:47.033086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f510da307e'
down_revision = 'af38be27fc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint('event_participants_ticket_id_fkey', type_='foreignkey')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('event_ticket_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event_participants', ['holder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_ticket_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('holder_id')

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('event_participants_ticket_id_fkey', 'event_tickets', ['ticket_id'], ['id'])

    # ### end Alembic commands ###
