"""added last ticket number field

Revision ID: b52c03f05106
Revises: b2efdb1d8caf
Create Date: 2025-01-05 23:54:06.996158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52c03f05106'
down_revision = 'b2efdb1d8caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ticket_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('last_ticket_number')

    # ### end Alembic commands ###
