"""added Note field

Revision ID: b5e20d54f826
Revises: 65a54f253b47
Create Date: 2025-01-17 15:56:16.636325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e20d54f826'
down_revision = '65a54f253b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
