"""added register datetime field

Revision ID: b9a443fae231
Revises: b52c03f05106
Create Date: 2025-01-07 16:30:41.458977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a443fae231'
down_revision = 'b52c03f05106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_datetime', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_column('register_datetime')

    # ### end Alembic commands ###
