"""added line ID field to the Participant model

Revision ID: d03656d46c5d
Revises: 5845204c4a96
Create Date: 2024-12-20 05:06:10.908702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03656d46c5d'
down_revision = '5845204c4a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_column('line_id')

    # ### end Alembic commands ###
