"""added fields to link tickets to participant

Revision ID: d8dd1cd5ac63
Revises: eee4a8a92896
Create Date: 2024-12-15 15:22:34.470737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dd1cd5ac63'
down_revision = 'eee4a8a92896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event_tickets', ['ticket_id'], ['id'])

    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event_participants', ['participant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###
